version: '2'
services:
  hexalink_image_sharing:
    image: "nguyenvinhlinh/image_sharing:0.0.3"
    container_name: "hexalink_image_sharing"
    ports:
      - "4000:4000"
    environment:
      - MIX_ENV=prod
      - APP_PORT=4000
      - APP_DOMAIN_NAME=image.hexalink.xyz
      - APP_ROOT_URL=http://image.hexalink.xyz:4000
      - APP_FILE_STORE_PATH=/image_sharing/uploads
      - DATABASE_HOSTNAME=hexalink_postgres_database
      - DATABASE_PORT=5432
      - DATABASE_NAME=image_sharing_db
      - DATABASE_USERNAME=nguyenvinhlinh
      - DATABASE_PASSWORD=nguyenvinhlinh
      - REPLACE_OS_VARS=true
      - FACEBOOK_APP_ID='1372612886139574'
    volumes: /hexalink_image_sharing/data/uploads:/image_sharing/uploads
  hexalink_postgres_database:
    container_name: "hexalink_postgres_database"
    image: 'postgres:latest'
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=nguyenvinhlinh
      - POSTGRES_PASSWORD=nguyenvinhlinh
      - POSTGRES_DB=image_sharing_db
      - PGDATA=/postgres_data
    volumes:
      - /hexalink_image_sharing/data/postgres_data:/image_sharing/postgres_data
